# Generated by Django 3.0.7 on 2020-06-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Title',
        ),
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.SlugField(blank=True),
        ),
    ]
